/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-primary": "var(--color-on-primary)",
        "tertiary": "var(--color-tertiary)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "inverse-surface": "var(--color-inverse-surface)",
        "surface-dim": "var(--color-surface-dim)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "surface-tint": "var(--color-surface-tint)",
        "tertiary-container": "var(--color-tertiary-container)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "secondary-container": "var(--color-secondary-container)",
        "error-container": "var(--color-error-container)",
        "surface": "var(--color-surface)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "outline-variant": "var(--color-outline-variant)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "background": "var(--color-background)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "outline": "var(--color-outline)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "primary-container": "var(--color-primary-container)",
        "primary": "var(--color-primary)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-error": "var(--color-on-error)",
        "primary-fixed": "var(--color-primary-fixed)",
        "secondary": "var(--color-secondary)",
        "error": "#ba1a1a",
        "on-background": "var(--color-on-background)",
        "surface-container-high": "var(--color-surface-container-high)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "surface-container": "var(--color-surface-container)",
        "on-error-container": "var(--color-on-error-container)",
        "on-secondary": "var(--color-on-secondary)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-surface": "var(--color-on-surface)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "risk-high": "#FF6B6B",
        "info": "#4D96FF"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "4px",
        "gutter": "24px",
        "container-max": "1440px",
        "shadow-offset": "4px",
        "margin-desktop": "40px",
        "border-width": "2px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "data-mono": ["14px", { lineHeight: "1", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
